import { FAQItem } from '../components/FAQ';

export const blogFAQs: FAQItem[] = [
  {
    question_da: 'Hvad handler AIBooking.dk\'s blog om?',
    question_en: "What is the AIBooking.dk blog about?",
    answer_da: 'Bloggen dækker AI-widgets, AI-telefonassistenter (inbound og outbound) og komplet AI-automatisering af reception og booking – med praktiske vinkler for klinikker, håndværkere, kontorer og webshops.',
    answer_en: 'The blog covers AI widgets, AI phone assistants (inbound and outbound), and complete AI automation of reception and booking — with practical angles for clinics, craftsmen, offices and webshops.',
    question_pt: 'Sobre o que é o blog da AIBooking.dk?',
    question_fr: 'De quoi parle le blog d\'AIBooking.dk ?',
    answer_pt: 'O blog aborda widgets de IA, assistentes telefónicos de IA (inbound e outbound) e a automatização completa de receção e marcação com IA — com abordagens práticas para clínicas, artesãos, escritórios e lojas online.',
    answer_fr: 'Le blog couvre les widgets IA, les assistants téléphoniques IA (entrants et sortants) et l\'automatisation complète de la réception et des réservations par IA — avec des angles pratiques pour les cliniques, artisans, bureaux et boutiques en ligne.',
  },
  {
    question_da: 'Er artiklerne relevante for mindre virksomheder?',
    question_en: 'Are the articles relevant for small businesses?',
    answer_da: 'Ja, en stor del af indholdet handler specifikt om, hvordan mindre firmaer og enkeltmandsvirksomheder får mest ud af automatisering, uden at skulle ansætte flere.',
    answer_en: 'Yes, a large part of the content is specifically about how smaller companies and one-person businesses get the most out of automation without needing to hire more people.',
    question_pt: 'Os artigos são relevantes para pequenas empresas?',
    question_fr: 'Les articles sont-ils pertinents pour les petites entreprises ?',
    answer_pt: 'Sim, grande parte do conteúdo é especificamente sobre como pequenas empresas e negócios unipessoais tiram o máximo partido da automatização sem precisarem de contratar mais pessoal.',
    answer_fr: 'Oui, une grande partie du contenu porte spécifiquement sur la façon dont les petites entreprises et les indépendants tirent le meilleur parti de l\'automatisation sans avoir besoin d\'embaucher davantage.',
  },
  {
    question_da: 'Hvordan hænger widget, telefon og booking sammen?',
    question_en: 'How do the widget, phone and booking fit together?',
    answer_da: 'Forbundet til samme kalender og kundejournal dækker de hinandens huller, så en henvendelse aldrig går tabt mellem kanalerne – det er temaet i vores "AI Totalløsning"-kategori.',
    answer_en: 'Connected to the same calendar and customer record, they cover each other\'s gaps so an enquiry is never lost between channels — that\'s the theme of our "AI Total Solution" category.',
    question_pt: 'Como se conjugam o widget, o telefone e as marcações?',
    question_fr: 'Comment le widget, le téléphone et la réservation s\'articulent-ils ?',
    answer_pt: 'Ligados ao mesmo calendário e ficha de cliente, cobrem as lacunas uns dos outros para que nenhum pedido se perca entre canais — esse é o tema da nossa categoria "Solução Total de IA".',
    answer_fr: 'Connectés au même calendrier et à la même fiche client, ils comblent mutuellement leurs lacunes afin qu\'aucune demande ne se perde entre les canaux — c\'est le thème de notre catégorie « Solution IA Totale ».',
  },
  {
    question_da: 'Kan jeg få hjælp til at vælge den rigtige løsning efter at have læst bloggen?',
    question_en: 'Can I get help choosing the right solution after reading the blog?',
    answer_da: 'Ja, book en gratis demo, så gennemgår vi, hvad der giver mest værdi for netop din virksomhed og branche.',
    answer_en: 'Yes, book a free demo and we\'ll walk through what gives the most value for your specific business and industry.',
    question_pt: 'Posso obter ajuda para escolher a solução certa depois de ler o blog?',
    question_fr: 'Puis-je obtenir de l\'aide pour choisir la bonne solution après avoir lu le blog ?',
    answer_pt: 'Sim, marque uma demonstração gratuita e mostramos-lhe o que traz mais valor para a sua empresa e setor específicos.',
    answer_fr: 'Oui, réservez une démo gratuite et nous passerons en revue ce qui apporte le plus de valeur à votre entreprise et à votre secteur spécifiques.',
  },
];

export const homeFAQs: FAQItem[] = [
  {
    question_da: 'Hvad er Aibooking.dk?',
    question_en: 'What is Aibooking.dk?',
    answer_da: 'Aibooking.dk er en AI-drevet reception, der håndterer indgående og udgående opkald, en chat-/talewidget på din hjemmeside og automatisk booking i din kalender – så du aldrig mister en kunde, fordi ingen kunne svare.',
    answer_en: 'Aibooking.dk is an AI-driven reception that handles inbound and outbound calls, a chat/voice widget on your website, and automatic calendar booking — so you never lose a customer just because no one was free to answer.',
    question_pt: 'O que é a Aibooking.dk?',
    question_fr: 'Qu\'est-ce qu\'Aibooking.dk ?',
    answer_pt: 'A Aibooking.dk é uma receção alimentada por IA que gere chamadas recebidas e efetuadas, um widget de chat/voz no seu site e marcações automáticas no calendário — para nunca perder um cliente só porque ninguém estava livre para atender.',
    answer_fr: 'Aibooking.dk est une réception pilotée par IA qui gère les appels entrants et sortants, un widget de chat/voix sur votre site web, et la prise de rendez-vous automatique dans votre calendrier — pour ne jamais perdre un client simplement parce que personne n\'était disponible pour répondre.',
  },
  {
    question_da: 'Hvor meget tid kan jeg spare med en AI-receptionist?',
    question_en: 'How much time can an AI receptionist save me?',
    answer_da: 'Det afhænger af, hvor mange opkald og henvendelser din virksomhed får, men de fleste kunder mærker mest på de rutinemæssige spørgsmål om åbningstider, priser og ledig tid, som ellers optager medarbejdertid hver dag. Den frigjorte tid er penge, du kan bruge på arbejde, der faktisk betaler sig.',
    answer_en: 'It depends on how many calls and enquiries your business gets, but most customers notice it most on the routine questions about opening hours, prices and availability that otherwise take up staff time every day. That freed-up time is money you can redirect to work that actually pays.',
    question_pt: 'Quanto tempo posso poupar com uma receção de IA?',
    question_fr: 'Combien de temps une réceptionniste IA peut-elle me faire gagner ?',
    answer_pt: 'Depende do número de chamadas e pedidos que a sua empresa recebe, mas a maioria dos clientes nota mais o efeito nas perguntas rotineiras sobre horários, preços e disponibilidade, que de outra forma ocupam tempo da equipa todos os dias. Esse tempo libertado é dinheiro que pode direcionar para trabalho que realmente compensa.',
    answer_fr: 'Cela dépend du nombre d\'appels et de demandes que reçoit votre entreprise, mais la plupart des clients constatent l\'effet surtout sur les questions courantes concernant les horaires, les prix et les disponibilités, qui autrement occupent le personnel chaque jour. Ce temps libéré représente de l\'argent que vous pouvez consacrer à un travail réellement rentable.',
  },
  {
    question_da: 'Fungerer det for mindre virksomheder og enkeltmandsfirmaer?',
    question_en: 'Does this work for small businesses and one-person companies?',
    answer_da: 'Ja – faktisk mærker mindre firmaer ofte den største effekt, fordi der ikke er en kollega til at tage over, når ejeren er optaget. AI-receptionisten fungerer som en altid-tilgængelig medarbejder uden at kræve en ansættelse.',
    answer_en: 'Yes — small businesses often feel the biggest impact, precisely because there is no colleague to step in when the owner is busy. The AI receptionist acts like an always-available employee without requiring a new hire.',
    question_pt: 'Funciona para pequenas empresas e negócios unipessoais?',
    question_fr: 'Est-ce adapté aux petites entreprises et aux indépendants ?',
    answer_pt: 'Sim — as pequenas empresas sentem frequentemente o maior impacto, precisamente porque não há um colega para assumir quando o proprietário está ocupado. A receção de IA funciona como um colaborador sempre disponível, sem exigir uma nova contratação.',
    answer_fr: 'Oui — ce sont souvent les petites entreprises qui en ressentent le plus l\'impact, justement parce qu\'il n\'y a pas de collègue pour prendre le relais lorsque le dirigeant est occupé. La réceptionniste IA agit comme un employé toujours disponible, sans nécessiter d\'embauche.',
  },
  {
    question_da: 'Kan jeg bruge løsningen, hvis jeg driver en webshop?',
    question_en: 'Can I use this if I run a webshop?',
    answer_da: 'Ja. Widgeten besvarer produkt-, leverings- og returspørgsmål direkte på hjemmesiden, døgnet rundt, så en efterladt kurv i stedet bliver til en gennemført ordre.',
    answer_en: 'Yes. The widget answers product, shipping and return questions directly on your site, around the clock, turning what would have been an abandoned cart into a completed order.',
    question_pt: 'Posso usar isto se tiver uma loja online?',
    question_fr: 'Puis-je l\'utiliser si je gère une boutique en ligne ?',
    answer_pt: 'Sim. O widget responde a perguntas sobre produtos, envios e devoluções diretamente no seu site, a qualquer hora, transformando o que seria um carrinho abandonado numa encomenda concluída.',
    answer_fr: 'Oui. Le widget répond aux questions sur les produits, la livraison et les retours directement sur votre site, 24h/24, transformant ce qui aurait été un panier abandonné en commande finalisée.',
  },
  {
    question_da: 'Hvad koster det, og hvordan kommer jeg i gang?',
    question_en: 'What does it cost, and how do I get started?',
    answer_da: 'Se prisoversigten på siden, eller book en gratis demo, hvor vi gennemgår, hvad der giver mest værdi for netop din virksomhed – klinik, håndværker, kontor eller webshop.',
    answer_en: 'See the pricing overview on the page, or book a free demo where we walk through what gives the most value for your specific business — clinic, craftsman, office or webshop.',
    question_pt: 'Quanto custa e como começo?',
    question_fr: 'Combien ça coûte et comment démarrer ?',
    answer_pt: 'Consulte a tabela de preços na página, ou marque uma demonstração gratuita onde lhe mostramos o que traz mais valor para a sua empresa específica — clínica, artesão, escritório ou loja online.',
    answer_fr: 'Consultez la grille tarifaire sur la page, ou réservez une démo gratuite où nous passerons en revue ce qui apporte le plus de valeur à votre entreprise spécifique — clinique, artisan, bureau ou boutique en ligne.',
  },
];

export const widgetFAQs: FAQItem[] = [
  {
    question_da: 'Hvad kan AI-widgeten på min hjemmeside?',
    question_en: 'What can the AI widget on my website do?',
    answer_da: 'Widgeten svarer på besøgendes spørgsmål med det samme, tjekker ledig tid i din kalender og kan booke en aftale direkte – uden at nogen fra dit team behøver at være online.',
    answer_en: "The widget answers visitors' questions instantly, checks real availability in your calendar, and can book an appointment directly — without anyone on your team needing to be online.",
    question_pt: 'O que pode fazer o widget de IA no meu site?',
    question_fr: 'Que peut faire le widget IA sur mon site ?',
    answer_pt: 'O widget responde instantaneamente às perguntas dos visitantes, verifica a disponibilidade real no seu calendário e pode marcar uma consulta diretamente — sem que ninguém da sua equipa precise de estar online.',
    answer_fr: 'Le widget répond instantanément aux questions des visiteurs, vérifie les disponibilités réelles dans votre calendrier et peut réserver un rendez-vous directement — sans qu\'un membre de votre équipe ait besoin d\'être en ligne.',
  },
  {
    question_da: 'Kan widgeten booke direkte i min kalender?',
    question_en: 'Can the widget book directly into my calendar?',
    answer_da: 'Ja, når widgeten er forbundet til dit bookingsystem, kan den vise reelt ledige tider og bekræfte en aftale med det samme, i stedet for blot at videresende en besked.',
    answer_en: 'Yes, once connected to your booking system, the widget can show real available times and confirm an appointment on the spot, instead of just forwarding a message.',
    question_pt: 'O widget pode marcar diretamente no meu calendário?',
    question_fr: 'Le widget peut-il réserver directement dans mon calendrier ?',
    answer_pt: 'Sim, uma vez ligado ao seu sistema de marcações, o widget pode mostrar horários realmente disponíveis e confirmar uma marcação na hora, em vez de apenas encaminhar uma mensagem.',
    answer_fr: 'Oui, une fois connecté à votre système de réservation, le widget peut afficher les créneaux réellement disponibles et confirmer un rendez-vous sur-le-champ, plutôt que de simplement transmettre un message.',
  },
  {
    question_da: 'Er widgeten god til webshops?',
    question_en: 'Is the widget good for webshops?',
    answer_da: 'Meget af den trafik en webshop får ligger uden for åbningstiden. Widgeten svarer på produkt-, størrelses- og leveringsspørgsmål med det samme, hvilket reducerer efterladte kurve.',
    answer_en: 'Much of the traffic a webshop gets happens outside opening hours. The widget answers product, sizing and shipping questions instantly, which reduces abandoned carts.',
    question_pt: 'O widget é adequado para lojas online?',
    question_fr: 'Le widget est-il adapté aux boutiques en ligne ?',
    answer_pt: 'Grande parte do tráfego de uma loja online ocorre fora do horário comercial. O widget responde instantaneamente a perguntas sobre produtos, tamanhos e envios, o que reduz os carrinhos abandonados.',
    answer_fr: 'Une grande partie du trafic d\'une boutique en ligne survient en dehors des heures d\'ouverture. Le widget répond instantanément aux questions sur les produits, les tailles et la livraison, ce qui réduit les paniers abandonnés.',
  },
  {
    question_da: 'Kan patienter booke tid hos min klinik uden for åbningstid?',
    question_en: 'Can patients book an appointment at my clinic outside opening hours?',
    answer_da: 'Ja. Widgeten lader patienter se og booke ledige tider om aftenen og i weekenden, så det ikke kræver et telefonopkald i åbningstiden.',
    answer_en: 'Yes. The widget lets patients see and book available times in the evening and on weekends, without requiring a phone call during opening hours.',
    question_pt: 'Os pacientes podem marcar consulta na minha clínica fora do horário de funcionamento?',
    question_fr: 'Les patients peuvent-ils prendre rendez-vous dans ma clinique en dehors des heures d\'ouverture ?',
    answer_pt: 'Sim. O widget permite que os pacientes vejam e marquem horários disponíveis à noite e aos fins de semana, sem precisarem de telefonar durante o horário de funcionamento.',
    answer_fr: 'Oui. Le widget permet aux patients de consulter et réserver des créneaux disponibles le soir et le week-end, sans avoir besoin d\'appeler pendant les heures d\'ouverture.',
  },
  {
    question_da: 'Hvad sker der med de persondata, widgeten indsamler?',
    question_en: 'What happens to the personal data the widget collects?',
    answer_da: 'Data håndteres i overensstemmelse med GDPR – vi indsamler kun det, der er nødvendigt for booking eller henvendelse, og kan give dig detaljer om opbevaring og sletning ved henvendelse.',
    answer_en: 'Data is handled in accordance with GDPR — we only collect what is necessary for a booking or enquiry, and can provide details on storage and deletion on request.',
    question_pt: 'O que acontece aos dados pessoais recolhidos pelo widget?',
    question_fr: 'Que deviennent les données personnelles collectées par le widget ?',
    answer_pt: 'Os dados são tratados em conformidade com o RGPD — apenas recolhemos o que é necessário para uma marcação ou pedido, e podemos fornecer detalhes sobre armazenamento e eliminação a pedido.',
    answer_fr: 'Les données sont traitées conformément au RGPD — nous ne collectons que ce qui est nécessaire à une réservation ou une demande, et pouvons fournir des détails sur la conservation et la suppression sur demande.',
  },
];

export const industriesFAQs: FAQItem[] = [
  {
    question_da: 'Hvilke brancher passer AI-automatisering til?',
    question_en: 'Which industries does AI automation fit?',
    answer_da: 'Løsningen bruges bredt af klinikker, håndværkere, kontor- og administrationsvirksomheder samt webshops – overalt hvor telefon- og hjemmesidehenvendelser skal håndteres konsekvent.',
    answer_en: 'The solution is used broadly by clinics, craftsmen, office and admin businesses, and webshops — anywhere phone and website enquiries need to be handled consistently.',
    question_pt: 'Para que setores serve a automatização com IA?',
    question_fr: 'À quels secteurs l\'automatisation IA convient-elle ?',
    answer_pt: 'A solução é amplamente utilizada por clínicas, artesãos, empresas de escritório e administração, e lojas online — em qualquer lugar onde os pedidos por telefone e site precisem de ser tratados de forma consistente.',
    answer_fr: 'La solution est largement utilisée par les cliniques, artisans, entreprises de bureau et d\'administration, ainsi que les boutiques en ligne — partout où les demandes par téléphone et par site web doivent être traitées de manière cohérente.',
  },
  {
    question_da: 'Skal jeg vælge mellem widget og telefonassistent?',
    question_en: 'Do I have to choose between the widget and the phone assistant?',
    answer_da: 'Nej, de fleste virksomheder får mest værdi ud af at koble dem sammen, så samtaler, der starter på hjemmesiden, kan fortsætte over telefonen uden at kunden skal gentage sig selv.',
    answer_en: "No, most businesses get the most value from connecting them, so a conversation that starts on the website can continue over the phone without the customer repeating themselves.",
    question_pt: 'Tenho de escolher entre o widget e o assistente telefónico?',
    question_fr: 'Dois-je choisir entre le widget et l\'assistant téléphonique ?',
    answer_pt: 'Não, a maioria das empresas obtém mais valor ao ligá-los, para que uma conversa iniciada no site possa continuar por telefone sem o cliente ter de se repetir.',
    answer_fr: 'Non, la plupart des entreprises tirent le plus de valeur en les connectant, afin qu\'une conversation commencée sur le site puisse se poursuivre par téléphone sans que le client ait à se répéter.',
  },
  {
    question_da: 'Kan mindre firmaer også have gavn af det?',
    question_en: 'Can smaller companies benefit too?',
    answer_da: 'Ja, ofte mest af alle – en mindre virksomhed har sjældent en backup, når den ene ansvarlige er optaget, og automatiseringen sikrer, at ingen henvendelse går tabt.',
    answer_en: 'Yes, often the most — a smaller business rarely has a backup when the one person responsible is busy, and automation ensures no enquiry gets lost.',
    question_pt: 'As empresas mais pequenas também podem beneficiar?',
    question_fr: 'Les petites entreprises peuvent-elles aussi en bénéficier ?',
    answer_pt: 'Sim, muitas vezes são as que mais beneficiam — uma empresa pequena raramente tem um substituto quando a pessoa responsável está ocupada, e a automatização garante que nenhum pedido se perde.',
    answer_fr: 'Oui, souvent plus que les autres — une petite entreprise dispose rarement d\'un remplaçant lorsque la personne responsable est occupée, et l\'automatisation garantit qu\'aucune demande n\'est perdue.',
  },
  {
    question_da: 'Hvordan sikrer det, at jeg aldrig mister en kunde?',
    question_en: 'How does it ensure I never lose a customer?',
    answer_da: 'Ved at dække alle kontaktpunkter – widget, telefon og opfølgning – i ét system, så en henvendelse aldrig forsvinder i hullet mellem kanalerne.',
    answer_en: 'By covering every touchpoint — widget, phone and follow-up — in one system, so an enquiry never falls through the gap between channels.',
    question_pt: 'Como garante que nunca perco um cliente?',
    question_fr: 'Comment garantit-elle que je ne perds jamais un client ?',
    answer_pt: 'Cobrindo todos os pontos de contacto — widget, telefone e acompanhamento — num único sistema, para que nenhum pedido se perca entre canais.',
    answer_fr: 'En couvrant chaque point de contact — widget, téléphone et suivi — au sein d\'un seul système, afin qu\'aucune demande ne se perde entre les canaux.',
  },
  {
    question_da: 'Kan jeg se, hvordan det virker for netop min branche?',
    question_en: 'Can I see how it works for my specific industry?',
    answer_da: 'Ja, se branchesiderne for klinik, håndværker, kontor og webshop, eller book en gratis demo tilpasset din virksomhed.',
    answer_en: 'Yes, see the industry pages for clinic, craftsman, office and webshop, or book a free demo tailored to your business.',
    question_pt: 'Posso ver como funciona especificamente para o meu setor?',
    question_fr: 'Puis-je voir comment cela fonctionne pour mon secteur spécifique ?',
    answer_pt: 'Sim, consulte as páginas de setores para clínica, artesão, escritório e loja online, ou marque uma demonstração gratuita adaptada à sua empresa.',
    answer_fr: 'Oui, consultez les pages sectorielles pour clinique, artisan, bureau et boutique en ligne, ou réservez une démo gratuite adaptée à votre entreprise.',
  },
];

export const healthcareFAQs: FAQItem[] = [
  {
    question_da: 'Kan en AI-telefonassistent reducere udeblivelser på min klinik?',
    question_en: 'Can an AI phone assistant reduce no-shows at my clinic?',
    answer_da: 'Ja. Automatiske påmindelsesopkald før en aftale reducerer antallet af patienter, der simpelthen glemmer at møde op, uden at det kræver ekstra arbejde fra receptionen.',
    answer_en: "Yes. Automatic reminder calls ahead of an appointment reduce the number of patients who simply forget to show up, without requiring extra work from reception.",
    question_pt: 'Um assistente telefónico de IA pode reduzir as faltas na minha clínica?',
    question_fr: 'Un assistant téléphonique IA peut-il réduire les rendez-vous manqués dans ma clinique ?',
    answer_pt: 'Sim. As chamadas automáticas de lembrete antes de uma consulta reduzem o número de pacientes que simplesmente se esquecem de comparecer, sem exigir trabalho extra da receção.',
    answer_fr: 'Oui. Les appels de rappel automatiques avant un rendez-vous réduisent le nombre de patients qui oublient simplement de se présenter, sans travail supplémentaire pour la réception.',
  },
  {
    question_da: 'Kan patienter booke tid uden at ringe?',
    question_en: 'Can patients book an appointment without calling?',
    answer_da: 'Ja, via widgeten på hjemmesiden kan patienter se ledig tid og booke direkte, også uden for klinikkens åbningstid.',
    answer_en: 'Yes, through the widget on your website, patients can see availability and book directly, even outside the clinic\'s opening hours.',
    question_pt: 'Os pacientes podem marcar consulta sem telefonar?',
    question_fr: 'Les patients peuvent-ils prendre rendez-vous sans appeler ?',
    answer_pt: 'Sim, através do widget no seu site, os pacientes podem ver a disponibilidade e marcar diretamente, mesmo fora do horário de funcionamento da clínica.',
    answer_fr: 'Oui, grâce au widget sur votre site, les patients peuvent consulter les disponibilités et réserver directement, même en dehors des heures d\'ouverture de la clinique.',
  },
  {
    question_da: 'Hvad sker der, hvis en patient ringer med et akut spørgsmål?',
    question_en: 'What happens if a patient calls with an urgent question?',
    answer_da: 'AI-telefonassistenten vurderer henvendelsen og stiller den videre til klinikkens personale, når det er relevant, i stedet for at forsøge at afgøre det selv.',
    answer_en: "The AI phone assistant assesses the enquiry and transfers it to the clinic's staff when relevant, rather than trying to decide it on its own.",
    question_pt: 'O que acontece se um paciente ligar com uma questão urgente?',
    question_fr: 'Que se passe-t-il si un patient appelle pour une question urgente ?',
    answer_pt: 'O assistente telefónico de IA avalia o pedido e transfere-o para a equipa da clínica quando relevante, em vez de tentar decidir sozinho.',
    answer_fr: 'L\'assistant téléphonique IA évalue la demande et la transfère au personnel de la clinique lorsque cela est pertinent, plutôt que de tenter de trancher seul.',
  },
  {
    question_da: 'Frigør det tid for min reception?',
    question_en: 'Does this free up time for my reception?',
    answer_da: 'Ja, rutineopkald om booking, åbningstider og priser bliver besvaret automatisk, så receptionen kan bruge mere tid på patienterne, der er til stede.',
    answer_en: 'Yes, routine calls about booking, opening hours and prices are answered automatically, so reception can spend more time with the patients in front of them.',
    question_pt: 'Isto liberta tempo para a minha receção?',
    question_fr: 'Cela libère-t-il du temps pour ma réception ?',
    answer_pt: 'Sim, as chamadas rotineiras sobre marcações, horários e preços são atendidas automaticamente, para que a receção possa dedicar mais tempo aos pacientes presentes.',
    answer_fr: 'Oui, les appels courants concernant les réservations, les horaires et les tarifs sont traités automatiquement, ce qui permet à la réception de consacrer plus de temps aux patients présents.',
  },
  {
    question_da: 'Er løsningen GDPR-sikker for patientdata?',
    question_en: 'Is the solution GDPR-compliant for patient data?',
    answer_da: 'Ja, data håndteres sikkert og i overensstemmelse med gældende lovgivning. Kontakt os for detaljer om databehandleraftale og opbevaring.',
    answer_en: 'Yes, data is handled securely and in accordance with applicable regulations. Contact us for details on the data processing agreement and retention.',
    question_pt: 'A solução está em conformidade com o RGPD para dados de pacientes?',
    question_fr: 'La solution est-elle conforme au RGPD pour les données des patients ?',
    answer_pt: 'Sim, os dados são tratados com segurança e em conformidade com a legislação aplicável. Contacte-nos para detalhes sobre o acordo de tratamento de dados e retenção.',
    answer_fr: 'Oui, les données sont traitées en toute sécurité et conformément à la réglementation applicable. Contactez-nous pour plus de détails sur l\'accord de traitement des données et la durée de conservation.',
  },
];

export const craftsmanFAQs: FAQItem[] = [
  {
    question_da: 'Jeg kan sjældent tage telefonen midt i en opgave – hjælper det her?',
    question_en: "I can rarely answer the phone mid-job — does this help?",
    answer_da: 'Ja, det er præcis den situation, løsningen er bygget til. AI-telefonassistenten besvarer opkaldet, indhenter adresse, opgavetype og hastegrad, og booker en tid til opringning eller besøg.',
    answer_en: 'Yes, that\'s exactly the situation this is built for. The AI phone assistant answers the call, gathers the address, job type and urgency, and books a callback or visit time.',
    question_pt: 'Raramente consigo atender o telefone a meio de um trabalho — isto ajuda?',
    question_fr: 'Je peux rarement répondre au téléphone en plein chantier — est-ce que ça aide ?',
    answer_pt: 'Sim, é exatamente para essa situação que isto foi criado. O assistente telefónico de IA atende a chamada, recolhe a morada, o tipo de trabalho e a urgência, e marca um horário para retorno ou visita.',
    answer_fr: 'Oui, c\'est exactement la situation pour laquelle c\'est conçu. L\'assistant téléphonique IA répond à l\'appel, recueille l\'adresse, le type d\'intervention et l\'urgence, et planifie un rappel ou une visite.',
  },
  {
    question_da: 'Kan kunder booke et opgavebesøg via hjemmesiden?',
    question_en: 'Can customers book a job visit through the website?',
    answer_da: 'Ja, widgeten kan tage imod opgaveforespørgsler med de nødvendige detaljer direkte fra hjemmesiden, så du kan prioritere dagen, før du ringer tilbage.',
    answer_en: "Yes, the widget can take job requests with the necessary details directly from the website, so you can prioritize the day before you call back.",
    question_pt: 'Os clientes podem marcar uma visita através do site?',
    question_fr: 'Les clients peuvent-ils réserver une visite via le site web ?',
    answer_pt: 'Sim, o widget pode recolher pedidos de trabalho com os detalhes necessários diretamente a partir do site, para que possa organizar o dia antes de retornar a chamada.',
    answer_fr: 'Oui, le widget peut recueillir les demandes d\'intervention avec les détails nécessaires directement depuis le site, afin que vous puissiez organiser votre journée avant de rappeler.',
  },
  {
    question_da: 'Fungerer det for en enkeltmandsvirksomhed?',
    question_en: 'Does it work for a one-person business?',
    answer_da: 'Ja, det er ofte der, effekten er størst – ingen opgaveforespørgsel går tabt, fordi telefonen ikke kunne besvares på stedet.',
    answer_en: 'Yes, this is often where the impact is greatest — no job request is lost because the phone couldn\'t be answered on the spot.',
    question_pt: 'Funciona para um negócio unipessoal?',
    question_fr: 'Est-ce adapté à une entreprise individuelle ?',
    answer_pt: 'Sim, é frequentemente aí que o impacto é maior — nenhum pedido de trabalho se perde por o telefone não poder ser atendido na hora.',
    answer_fr: 'Oui, c\'est souvent là que l\'impact est le plus fort — aucune demande d\'intervention n\'est perdue parce que le téléphone n\'a pas pu être décroché sur le moment.',
  },
  {
    question_da: 'Kan jeg få automatiske påmindelser sendt til kunder?',
    question_en: 'Can automatic reminders be sent to customers?',
    answer_da: 'Ja, AI-assistenten kan ringe eller sende en påmindelse forud for et aftalt besøg, så færre aftaler bliver glemt.',
    answer_en: 'Yes, the AI assistant can call or send a reminder ahead of a scheduled visit, so fewer appointments get forgotten.',
    question_pt: 'É possível enviar lembretes automáticos aos clientes?',
    question_fr: 'Peut-on envoyer des rappels automatiques aux clients ?',
    answer_pt: 'Sim, o assistente de IA pode ligar ou enviar um lembrete antes de uma visita agendada, para que menos marcações sejam esquecidas.',
    answer_fr: 'Oui, l\'assistant IA peut appeler ou envoyer un rappel avant une visite planifiée, pour que moins de rendez-vous soient oubliés.',
  },
  {
    question_da: 'Hvor lang tid tager det at komme i gang?',
    question_en: 'How long does it take to get started?',
    answer_da: 'Opsætningen tager typisk kort tid, og du kan starte med telefonassistenten alene, hvis det løser dit mest presserende problem lige nu.',
    answer_en: 'Setup typically takes a short time, and you can start with just the phone assistant if that solves your most pressing problem right now.',
    question_pt: 'Quanto tempo demora a começar?',
    question_fr: 'Combien de temps faut-il pour démarrer ?',
    answer_pt: 'A configuração demora tipicamente pouco tempo, e pode começar apenas com o assistente telefónico se isso resolver o seu problema mais urgente agora.',
    answer_fr: 'La mise en place prend généralement peu de temps, et vous pouvez commencer uniquement avec l\'assistant téléphonique si cela résout votre problème le plus urgent dès maintenant.',
  },
];

export const officeFAQs: FAQItem[] = [
  {
    question_da: 'Hvordan hjælper det kontor- og administrationsopgaver?',
    question_en: 'How does this help office and admin work?',
    answer_da: 'Rutineopkald om status, ændringer og generelle spørgsmål bliver håndteret automatisk, så personalet får længere, uafbrudte perioder til fokuseret arbejde.',
    answer_en: 'Routine calls about status, changes and general questions are handled automatically, giving staff longer, uninterrupted stretches for focused work.',
    question_pt: 'Como é que isto ajuda o trabalho de escritório e administração?',
    question_fr: 'Comment cela aide-t-il le travail de bureau et administratif ?',
    answer_pt: 'As chamadas rotineiras sobre estado, alterações e perguntas gerais são tratadas automaticamente, dando à equipa períodos mais longos e ininterruptos para trabalho concentrado.',
    answer_fr: 'Les appels courants concernant le statut, les modifications et les questions générales sont traités automatiquement, offrant au personnel des plages plus longues et ininterrompues pour un travail concentré.',
  },
  {
    question_da: 'Kan systemet håndtere både opkald og hjemmesidehenvendelser?',
    question_en: 'Can the system handle both calls and website enquiries?',
    answer_da: 'Ja, telefonassistenten og widgeten deler den samme information, så svarene er konsistente uanset kanal.',
    answer_en: 'Yes, the phone assistant and widget share the same information, so answers are consistent regardless of channel.',
    question_pt: 'O sistema consegue gerir tanto chamadas como pedidos pelo site?',
    question_fr: 'Le système peut-il gérer à la fois les appels et les demandes via le site ?',
    answer_pt: 'Sim, o assistente telefónico e o widget partilham a mesma informação, para que as respostas sejam consistentes independentemente do canal.',
    answer_fr: 'Oui, l\'assistant téléphonique et le widget partagent les mêmes informations, garantissant des réponses cohérentes quel que soit le canal.',
  },
  {
    question_da: 'Kan jeg tilpasse, hvilke opkald der bliver stillet videre?',
    question_en: 'Can I customize which calls get transferred?',
    answer_da: 'Ja, I definerer sammen med os, hvilke typer henvendelser AI-assistenten skal håndtere selv, og hvilke der altid skal videre til et menneske.',
    answer_en: 'Yes, together we define which types of enquiries the AI assistant should handle on its own, and which should always go to a person.',
    question_pt: 'Posso personalizar que chamadas são transferidas?',
    question_fr: 'Puis-je personnaliser quels appels sont transférés ?',
    answer_pt: 'Sim, definimos juntos que tipos de pedidos o assistente de IA deve tratar sozinho e quais devem ser sempre encaminhados para uma pessoa.',
    answer_fr: 'Oui, nous définissons ensemble quels types de demandes l\'assistant IA doit traiter seul, et lesquelles doivent toujours être transmises à une personne.',
  },
  {
    question_da: 'Er det egnet til mindre administrationsteams?',
    question_en: 'Is this suitable for smaller admin teams?',
    answer_da: 'Ja, especially for teams uden en dedikeret receptionist – automatiseringen dækker de rutinemæssige henvendelser, teamet ellers selv skulle tage.',
    answer_en: 'Yes, especially for teams without a dedicated receptionist — automation covers the routine enquiries the team would otherwise have to take themselves.',
    question_pt: 'É adequado para equipas administrativas mais pequenas?',
    question_fr: 'Est-ce adapté aux petites équipes administratives ?',
    answer_pt: 'Sim, especialmente para equipas sem receção dedicada — a automatização cobre os pedidos rotineiros que a equipa teria de tratar de outra forma.',
    answer_fr: 'Oui, en particulier pour les équipes sans réceptionniste dédié — l\'automatisation prend en charge les demandes courantes que l\'équipe devrait sinon traiter elle-même.',
  },
  {
    question_da: 'Hvordan kommer jeg i gang?',
    question_en: 'How do I get started?',
    answer_da: 'Book en gratis demo, så gennemgår vi jeres nuværende opkaldsmønster og finder den bedste startopsætning for jer.',
    answer_en: 'Book a free demo, and we\'ll go through your current call pattern and find the best starting setup for your team.',
    question_pt: 'Como começo?',
    question_fr: 'Comment démarrer ?',
    answer_pt: 'Marque uma demonstração gratuita e analisamos o seu padrão atual de chamadas para encontrar a melhor configuração inicial para a sua equipa.',
    answer_fr: 'Réservez une démo gratuite, et nous passerons en revue votre schéma d\'appels actuel pour trouver la meilleure configuration de départ pour votre équipe.',
  },
];

export const ecommerceFAQs: FAQItem[] = [
  {
    question_da: 'Kan AI-widgeten reducere efterladte kurve i min webshop?',
    question_en: 'Can the AI widget reduce abandoned carts in my webshop?',
    answer_da: 'Ja. Mange kurve bliver efterladt på grund af et ubesvaret spørgsmål om størrelse, levering eller retur. Widgeten svarer med det samme, også uden for åbningstid.',
    answer_en: 'Yes. Many carts are abandoned because of an unanswered question about size, shipping or returns. The widget answers instantly, even outside opening hours.',
    question_pt: 'O widget de IA pode reduzir os carrinhos abandonados na minha loja online?',
    question_fr: 'Le widget IA peut-il réduire les paniers abandonnés dans ma boutique en ligne ?',
    answer_pt: 'Sim. Muitos carrinhos são abandonados devido a uma pergunta sem resposta sobre tamanho, envio ou devoluções. O widget responde instantaneamente, mesmo fora do horário comercial.',
    answer_fr: 'Oui. De nombreux paniers sont abandonnés à cause d\'une question sans réponse sur la taille, la livraison ou les retours. Le widget répond instantanément, même en dehors des heures d\'ouverture.',
  },
  {
    question_da: 'Kan widgeten svare på spørgsmål om ordrestatus?',
    question_en: 'Can the widget answer order status questions?',
    answer_da: 'Ja, når den er forbundet til din ordredata, kan den svare på status og leveringsspørgsmål uden at trække medarbejdere væk fra pakning og forsendelse.',
    answer_en: 'Yes, once connected to your order data, it can answer status and delivery questions without pulling staff away from picking and shipping.',
    question_pt: 'O widget pode responder a perguntas sobre o estado da encomenda?',
    question_fr: 'Le widget peut-il répondre aux questions sur le statut des commandes ?',
    answer_pt: 'Sim, uma vez ligado aos dados das suas encomendas, pode responder a perguntas sobre estado e entrega sem desviar a equipa da preparação e expedição.',
    answer_fr: 'Oui, une fois connecté à vos données de commande, il peut répondre aux questions de statut et de livraison sans détourner le personnel de la préparation et de l\'expédition.',
  },
  {
    question_da: 'Fungerer det sammen med min telefonsupport?',
    question_en: 'Does it work alongside my phone support?',
    answer_da: 'Ja, widget og telefonassistent deler samme kundedata, så en kunde, der starter i chatten og ringer bagefter, ikke skal forklare sig igen.',
    answer_en: 'Yes, the widget and phone assistant share the same customer data, so a customer who starts in chat and calls afterward doesn\'t have to explain themselves again.',
    question_pt: 'Funciona em conjunto com o meu apoio telefónico?',
    question_fr: 'Fonctionne-t-il avec mon support téléphonique ?',
    answer_pt: 'Sim, o widget e o assistente telefónico partilham os mesmos dados de cliente, para que um cliente que comece no chat e depois ligue não tenha de se explicar novamente.',
    answer_fr: 'Oui, le widget et l\'assistant téléphonique partagent les mêmes données client, afin qu\'un client qui commence par le chat puis appelle n\'ait pas à se réexpliquer.',
  },
  {
    question_da: 'Kan komplekse sager blive sendt videre til et menneske?',
    question_en: 'Can complex cases be handed off to a person?',
    answer_da: 'Ja, beskadigede varer, tvister og andre sager uden for widgetens omfang bliver sendt videre med fuld kontekst i stedet for at gå i ring.',
    answer_en: 'Yes, damaged items, disputes and other cases outside the widget\'s scope are handed off with full context instead of going in circles.',
    question_pt: 'Os casos complexos podem ser encaminhados para uma pessoa?',
    question_fr: 'Les cas complexes peuvent-ils être transférés à une personne ?',
    answer_pt: 'Sim, artigos danificados, litígios e outros casos fora do âmbito do widget são encaminhados com todo o contexto, em vez de ficarem a andar em círculos.',
    answer_fr: 'Oui, les articles endommagés, les litiges et autres cas hors du champ du widget sont transmis avec le contexte complet, au lieu de tourner en rond.',
  },
  {
    question_da: 'Er det svært at integrere med min eksisterende webshop?',
    question_en: 'Is it hard to integrate with my existing webshop?',
    answer_da: 'Nej, opsætningen er designet til at komme hurtigt i gang – book en demo, så viser vi, hvordan det passer til jeres platform.',
    answer_en: 'No, setup is designed to get you running quickly — book a demo and we\'ll show you how it fits your platform.',
    question_pt: 'É difícil integrar com a minha loja online já existente?',
    question_fr: 'Est-ce difficile à intégrer à ma boutique en ligne existante ?',
    answer_pt: 'Não, a configuração foi pensada para começar rapidamente — marque uma demonstração e mostramos como se adapta à sua plataforma.',
    answer_fr: 'Non, la configuration est conçue pour vous permettre de démarrer rapidement — réservez une démo et nous vous montrerons comment cela s\'adapte à votre plateforme.',
  },
];

export const featuresFAQs: FAQItem[] = [
  {
    question_da: 'Hvilke funktioner er inkluderet?',
    question_en: 'What features are included?',
    answer_da: 'Intelligent opkaldsstyring, automatisk kalenderintegration, en AI-widget til hjemmesiden, automatiske påmindelser og opfølgning, samt et samlet dashboard over alle henvendelser.',
    answer_en: 'Intelligent call handling, automatic calendar integration, an AI widget for your website, automatic reminders and follow-up, and a single dashboard covering every enquiry.',
    question_pt: 'Que funcionalidades estão incluídas?',
    question_fr: 'Quelles fonctionnalités sont incluses ?',
    answer_pt: 'Gestão inteligente de chamadas, integração automática de calendário, um widget de IA para o seu site, lembretes e acompanhamento automáticos, e um painel único que cobre todos os pedidos.',
    answer_fr: 'Gestion intelligente des appels, intégration automatique du calendrier, un widget IA pour votre site, rappels et suivi automatiques, et un tableau de bord unique couvrant toutes les demandes.',
  },
  {
    question_da: 'Kan jeg bruge widget og telefonassistent sammen?',
    question_en: 'Can I use the widget and phone assistant together?',
    answer_da: 'Ja, forbundet til samme kalender og kundejournal dækker de hinandens huller, så ingen henvendelse går tabt mellem kanalerne.',
    answer_en: 'Yes, connected to the same calendar and customer record, they cover each other\'s gaps so no enquiry is lost between channels.',
    question_pt: 'Posso usar o widget e o assistente telefónico em conjunto?',
    question_fr: 'Puis-je utiliser le widget et l\'assistant téléphonique ensemble ?',
    answer_pt: 'Sim, ligados ao mesmo calendário e ficha de cliente, cobrem as lacunas um do outro para que nenhum pedido se perca entre canais.',
    answer_fr: 'Oui, connectés au même calendrier et à la même fiche client, ils comblent mutuellement leurs lacunes afin qu\'aucune demande ne se perde entre les canaux.',
  },
  {
    question_da: 'Fungerer funktionerne på dansk?',
    question_en: 'Do the features work in Danish?',
    answer_da: 'Ja, systemet er bygget til at forstå naturligt, afslappet dansk, med engelsk tilgængeligt for internationale kunder.',
    answer_en: 'Yes, the system is built to understand natural, casual Danish, with English available for international customers.',
    question_pt: 'As funcionalidades funcionam em dinamarquês?',
    question_fr: 'Les fonctionnalités fonctionnent-elles en danois ?',
    answer_pt: 'Sim, o sistema foi criado para compreender dinamarquês natural e informal, com inglês disponível para clientes internacionais.',
    answer_fr: 'Oui, le système est conçu pour comprendre un danois naturel et courant, avec l\'anglais disponible pour les clients internationaux.',
  },
  {
    question_da: 'Kan jeg tilpasse, hvad AI\'en må håndtere selv?',
    question_en: 'Can I customize what the AI is allowed to handle on its own?',
    answer_da: 'Ja, I sætter grænserne sammen med os for, hvad der besvares automatisk, og hvad der altid sendes videre til et menneske.',
    answer_en: 'Yes, together we set the boundaries for what gets answered automatically and what always gets escalated to a person.',
    question_pt: 'Posso personalizar o que a IA pode tratar sozinha?',
    question_fr: 'Puis-je personnaliser ce que l\'IA est autorisée à gérer seule ?',
    answer_pt: 'Sim, definimos juntos os limites do que é respondido automaticamente e do que é sempre encaminhado para uma pessoa.',
    answer_fr: 'Oui, nous définissons ensemble les limites de ce qui est traité automatiquement et de ce qui est toujours transmis à une personne.',
  },
  {
    question_da: 'Hvordan overvåger jeg, hvordan det bliver brugt?',
    question_en: 'How do I monitor how it\'s being used?',
    answer_da: 'Et samlet dashboard viser alle opkald, chats og bookinger, så du altid har overblik uden at skulle tjekke flere systemer.',
    answer_en: 'A single dashboard shows every call, chat and booking, so you always have an overview without checking multiple systems.',
    question_pt: 'Como monitorizo a forma como está a ser utilizado?',
    question_fr: 'Comment puis-je suivre son utilisation ?',
    answer_pt: 'Um painel único mostra todas as chamadas, chats e marcações, para que tenha sempre uma visão geral sem ter de consultar vários sistemas.',
    answer_fr: 'Un tableau de bord unique affiche tous les appels, discussions et réservations, vous offrant toujours une vue d\'ensemble sans avoir à consulter plusieurs systèmes.',
  },
];

export const integrationsFAQs: FAQItem[] = [
  {
    question_da: 'Kan jeg forbinde løsningen til mit eksisterende bookingsystem?',
    question_en: 'Can I connect the solution to my existing booking system?',
    answer_da: 'Ja, systemet er bygget til at integrere med almindelige kalender- og bookingsystemer, så du undgår dobbeltbookinger og manuel afstemning.',
    answer_en: 'Yes, the system is built to integrate with common calendar and booking systems, so you avoid double bookings and manual reconciliation.',
    question_pt: 'Posso ligar a solução ao meu sistema de marcações existente?',
    question_fr: 'Puis-je connecter la solution à mon système de réservation existant ?',
    answer_pt: 'Sim, o sistema foi criado para integrar com sistemas comuns de calendário e marcações, evitando marcações duplicadas e reconciliação manual.',
    answer_fr: 'Oui, le système est conçu pour s\'intégrer aux systèmes de calendrier et de réservation courants, afin d\'éviter les doubles réservations et la réconciliation manuelle.',
  },
  {
    question_da: 'Skal jeg skifte system for at bruge AI-automatisering?',
    question_en: 'Do I have to switch systems to use AI automation?',
    answer_da: 'Nej, målet er at forbinde til det, du allerede bruger, ikke at erstatte det.',
    answer_en: 'No, the goal is to connect to what you already use, not replace it.',
    question_pt: 'Tenho de mudar de sistema para usar a automatização com IA?',
    question_fr: 'Dois-je changer de système pour utiliser l\'automatisation IA ?',
    answer_pt: 'Não, o objetivo é ligar-se ao que já utiliza, não substituí-lo.',
    answer_fr: 'Non, l\'objectif est de se connecter à ce que vous utilisez déjà, pas de le remplacer.',
  },
  {
    question_da: 'Hvilke integrationer understøttes?',
    question_en: 'Which integrations are supported?',
    answer_da: 'Se integrationssiden for en oversigt over kategorier – kalender, kommunikation og flere – eller kontakt os for at bekræfte din specifikke opsætning.',
    answer_en: 'See the integrations page for an overview of categories — calendar, communication and more — or contact us to confirm your specific setup.',
    question_pt: 'Que integrações são suportadas?',
    question_fr: 'Quelles intégrations sont prises en charge ?',
    answer_pt: 'Consulte a página de integrações para uma visão geral das categorias — calendário, comunicação e mais — ou contacte-nos para confirmar a sua configuração específica.',
    answer_fr: 'Consultez la page des intégrations pour un aperçu des catégories — calendrier, communication et plus — ou contactez-nous pour confirmer votre configuration spécifique.',
  },
  {
    question_da: 'Hvad sker der, hvis min platform ikke er understøttet direkte?',
    question_en: 'What happens if my platform isn\'t directly supported?',
    answer_da: 'Kontakt os – vi vurderer, hvad der er muligt, og finder ofte en løsning, selv når det ikke er en standardintegration.',
    answer_en: 'Contact us — we\'ll assess what\'s possible and often find a solution even when it isn\'t a standard integration.',
    question_pt: 'O que acontece se a minha plataforma não for diretamente suportada?',
    question_fr: 'Que se passe-t-il si ma plateforme n\'est pas directement prise en charge ?',
    answer_pt: 'Contacte-nos — avaliamos o que é possível e frequentemente encontramos uma solução mesmo quando não se trata de uma integração padrão.',
    answer_fr: 'Contactez-nous — nous évaluerons ce qui est possible et trouvons souvent une solution même lorsqu\'il ne s\'agit pas d\'une intégration standard.',
  },
  {
    question_da: 'Kræver integrationen teknisk arbejde fra min side?',
    question_en: 'Does the integration require technical work on my end?',
    answer_da: 'De fleste opsætninger kræver minimal indsats fra dig – vi hjælper med det meste af arbejdet undervejs.',
    answer_en: 'Most setups require minimal effort on your side — we handle most of the work along the way.',
    question_pt: 'A integração exige trabalho técnico da minha parte?',
    question_fr: 'L\'intégration nécessite-t-elle un travail technique de mon côté ?',
    answer_pt: 'A maioria das configurações exige um esforço mínimo da sua parte — tratamos da maior parte do trabalho ao longo do processo.',
    answer_fr: 'La plupart des configurations nécessitent un effort minimal de votre part — nous prenons en charge la majeure partie du travail.',
  },
];

export const demoFAQs: FAQItem[] = [
  {
    question_da: 'Hvad indeholder den gratis demo?',
    question_en: 'What does the free demo include?',
    answer_da: 'En gennemgang af widget og telefonassistent tilpasset din branche, samt adgang til at afprøve løsningen i praksis i en periode.',
    answer_en: 'A walkthrough of the widget and phone assistant tailored to your industry, plus access to try the solution in practice for a period.',
    question_pt: 'O que inclui a demonstração gratuita?',
    question_fr: 'Que comprend la démo gratuite ?',
    answer_pt: 'Uma apresentação do widget e do assistente telefónico adaptada ao seu setor, além de acesso para experimentar a solução na prática durante um período.',
    answer_fr: 'Une présentation du widget et de l\'assistant téléphonique adaptée à votre secteur, ainsi qu\'un accès pour tester la solution en pratique pendant une période.',
  },
  {
    question_da: 'Er der nogen binding under demoperioden?',
    question_en: 'Is there any commitment during the demo period?',
    answer_da: 'Nej, demoen er uforpligtende, så du kan vurdere værdien, før du beslutter dig.',
    answer_en: 'No, the demo is non-binding, so you can assess the value before deciding.',
    question_pt: 'Existe algum compromisso durante o período de demonstração?',
    question_fr: 'Y a-t-il un engagement pendant la période de démo ?',
    answer_pt: 'Não, a demonstração é sem compromisso, para que possa avaliar o valor antes de decidir.',
    answer_fr: 'Non, la démo est sans engagement, afin que vous puissiez évaluer sa valeur avant de vous décider.',
  },
  {
    question_da: 'Hvor lang tid tager det at booke en demo?',
    question_en: 'How long does it take to book a demo?',
    answer_da: 'Kun et par minutter – vælg en tid direkte via bookingkalenderen på siden.',
    answer_en: 'Just a couple of minutes — pick a time directly through the booking calendar on the page.',
    question_pt: 'Quanto tempo demora a marcar uma demonstração?',
    question_fr: 'Combien de temps faut-il pour réserver une démo ?',
    answer_pt: 'Apenas alguns minutos — escolha um horário diretamente no calendário de marcações da página.',
    answer_fr: 'Seulement quelques minutes — choisissez un créneau directement via le calendrier de réservation sur la page.',
  },
  {
    question_da: 'Kan demoen tilpasses min specifikke branche?',
    question_en: 'Can the demo be tailored to my specific industry?',
    answer_da: 'Ja, vi tilpasser gennemgangen til, om du driver en klinik, et håndværkerfirma, et kontor eller en webshop.',
    answer_en: 'Yes, we tailor the walkthrough to whether you run a clinic, a craftsman business, an office or a webshop.',
    question_pt: 'A demonstração pode ser adaptada ao meu setor específico?',
    question_fr: 'La démo peut-elle être adaptée à mon secteur spécifique ?',
    answer_pt: 'Sim, adaptamos a apresentação consoante geste uma clínica, um negócio de artesão, um escritório ou uma loja online.',
    answer_fr: 'Oui, nous adaptons la présentation selon que vous dirigez une clinique, une entreprise artisanale, un bureau ou une boutique en ligne.',
  },
  {
    question_da: 'Hvad sker der efter demoen?',
    question_en: 'What happens after the demo?',
    answer_da: 'Hvis det er relevant for dig, hjælper vi med opsætningen trin for trin, startende med det, der løser dit mest presserende problem.',
    answer_en: 'If it\'s a fit, we help with setup step by step, starting with whatever solves your most pressing problem.',
    question_pt: 'O que acontece depois da demonstração?',
    question_fr: 'Que se passe-t-il après la démo ?',
    answer_pt: 'Se for adequado, ajudamos na configuração passo a passo, começando pelo que resolve o seu problema mais urgente.',
    answer_fr: 'Si cela vous convient, nous vous aidons dans la configuration étape par étape, en commençant par ce qui résout votre problème le plus urgent.',
  },
];

export const contactFAQs: FAQItem[] = [
  {
    question_da: 'Hvordan kommer jeg i kontakt med jer?',
    question_en: 'How do I get in touch with you?',
    answer_da: 'Ring på +45 91952794, send en email, eller udfyld kontaktformularen på siden, så vender vi tilbage inden for 24 timer.',
    answer_en: 'Call +45 91952794, send an email, or fill in the contact form on the page, and we\'ll get back to you within 24 hours.',
    question_pt: 'Como posso entrar em contacto convosco?',
    question_fr: 'Comment puis-je vous contacter ?',
    answer_pt: 'Ligue para +45 91952794, envie um email, ou preencha o formulário de contacto na página, e responderemos no prazo de 24 horas.',
    answer_fr: 'Appelez le +45 91952794, envoyez un e-mail, ou remplissez le formulaire de contact sur la page, et nous vous répondrons sous 24 heures.',
  },
  {
    question_da: 'Kan I hjælpe mig med at vælge den rigtige løsning?',
    question_en: 'Can you help me choose the right solution?',
    answer_da: 'Ja, fortæl os om din virksomhed, så anbefaler vi, om widget, telefonassistent eller en samlet totalløsning giver mest mening.',
    answer_en: 'Yes, tell us about your business and we\'ll recommend whether the widget, phone assistant, or a combined total solution makes the most sense.',
    question_pt: 'Podem ajudar-me a escolher a solução certa?',
    question_fr: 'Pouvez-vous m\'aider à choisir la bonne solution ?',
    answer_pt: 'Sim, fale-nos sobre a sua empresa e recomendamos se o widget, o assistente telefónico ou uma solução total combinada faz mais sentido.',
    answer_fr: 'Oui, parlez-nous de votre entreprise et nous vous recommanderons si le widget, l\'assistant téléphonique, ou une solution totale combinée est la plus pertinente.',
  },
  {
    question_da: 'Tilbyder I support på dansk?',
    question_en: 'Do you offer support in Danish?',
    answer_da: 'Ja, vores supportteam er dansk og svarer på både dansk og engelsk.',
    answer_en: 'Yes, our support team is Danish and responds in both Danish and English.',
    question_pt: 'Oferecem apoio em dinamarquês?',
    question_fr: 'Proposez-vous un support en danois ?',
    answer_pt: 'Sim, a nossa equipa de apoio é dinamarquesa e responde tanto em dinamarquês como em inglês.',
    answer_fr: 'Oui, notre équipe de support est danoise et répond aussi bien en danois qu\'en anglais.',
  },
  {
    question_da: 'Hvor hurtigt kan jeg forvente svar?',
    question_en: 'How quickly can I expect a response?',
    answer_da: 'Vi bestræber os på at svare inden for 24 timer på hverdage.',
    answer_en: 'We aim to respond within 24 hours on business days.',
    question_pt: 'Com que rapidez posso esperar uma resposta?',
    question_fr: 'À quelle vitesse puis-je espérer une réponse ?',
    answer_pt: 'Procuramos responder no prazo de 24 horas em dias úteis.',
    answer_fr: 'Nous visons à répondre sous 24 heures les jours ouvrés.',
  },
  {
    question_da: 'Kan jeg booke en demo i stedet for at skrive?',
    question_en: 'Can I book a demo instead of writing in?',
    answer_da: 'Ja, brug linket til at booke en gratis demo direkte, hvis du hellere vil se løsningen i praksis.',
    answer_en: 'Yes, use the link to book a free demo directly if you\'d rather see the solution in practice.',
    question_pt: 'Posso marcar uma demonstração em vez de escrever?',
    question_fr: 'Puis-je réserver une démo au lieu d\'écrire ?',
    answer_pt: 'Sim, use o link para marcar diretamente uma demonstração gratuita se preferir ver a solução na prática.',
    answer_fr: 'Oui, utilisez le lien pour réserver directement une démo gratuite si vous préférez voir la solution en pratique.',
  },
];

export const aboutFAQs: FAQItem[] = [
  {
    question_da: 'Hvem står bag Aibooking.dk?',
    question_en: 'Who is behind Aibooking.dk?',
    answer_da: 'Aibooking.dk er bygget til danske virksomheder, der vil automatisere reception og booking uden at gå på kompromis med kundeoplevelsen.',
    answer_en: 'Aibooking.dk is built for Danish businesses that want to automate reception and booking without compromising the customer experience.',
    question_pt: 'Quem está por trás da Aibooking.dk?',
    question_fr: 'Qui se cache derrière Aibooking.dk ?',
    answer_pt: 'A Aibooking.dk foi criada para empresas dinamarquesas que querem automatizar a receção e as marcações sem comprometer a experiência do cliente.',
    answer_fr: 'Aibooking.dk est conçue pour les entreprises danoises qui souhaitent automatiser la réception et les réservations sans compromettre l\'expérience client.',
  },
  {
    question_da: 'Hvorfor skulle jeg vælge Aibooking.dk frem for et andet system?',
    question_en: 'Why should I choose Aibooking.dk over another system?',
    answer_da: 'Løsningen er bygget specifikt til det danske marked, med naturligt dansk sprog og fokus på at samle widget, telefon og booking i ét sammenhængende system.',
    answer_en: 'The solution is built specifically for the Danish market, with natural Danish language and a focus on combining widget, phone and booking into one connected system.',
    question_pt: 'Porque deveria escolher a Aibooking.dk em vez de outro sistema?',
    question_fr: 'Pourquoi choisir Aibooking.dk plutôt qu\'un autre système ?',
    answer_pt: 'A solução foi criada especificamente para o mercado dinamarquês, com linguagem natural em dinamarquês e foco em combinar widget, telefone e marcações num único sistema integrado.',
    answer_fr: 'La solution est conçue spécifiquement pour le marché danois, avec un danois naturel et l\'objectif de réunir widget, téléphone et réservation dans un système unique et connecté.',
  },
  {
    question_da: 'Hvilke virksomheder passer produktet bedst til?',
    question_en: 'Which businesses is the product best suited for?',
    answer_da: 'Klinikker, håndværkere, kontor- og administrationsvirksomheder og webshops, der modtager løbende telefon- og hjemmesidehenvendelser.',
    answer_en: 'Clinics, craftsmen, office and admin businesses, and webshops that receive ongoing phone and website enquiries.',
    question_pt: 'Para que empresas é mais indicado o produto?',
    question_fr: 'À quelles entreprises le produit convient-il le mieux ?',
    answer_pt: 'Clínicas, artesãos, empresas de escritório e administração, e lojas online que recebem pedidos contínuos por telefone e site.',
    answer_fr: 'Cliniques, artisans, entreprises de bureau et d\'administration, et boutiques en ligne recevant des demandes continues par téléphone et par site web.',
  },
  {
    question_da: 'Er data sikre hos jer?',
    question_en: 'Is data safe with you?',
    answer_da: 'Ja, alle data håndteres sikkert og i overensstemmelse med dansk og europæisk lovgivning.',
    answer_en: 'Yes, all data is handled securely and in accordance with Danish and European regulations.',
    question_pt: 'Os dados estão seguros convosco?',
    question_fr: 'Mes données sont-elles en sécurité chez vous ?',
    answer_pt: 'Sim, todos os dados são tratados com segurança e em conformidade com a legislação dinamarquesa e europeia.',
    answer_fr: 'Oui, toutes les données sont traitées en toute sécurité et conformément à la réglementation danoise et européenne.',
  },
  {
    question_da: 'Hvordan kommer jeg i gang med at samarbejde med jer?',
    question_en: 'How do I get started working with you?',
    answer_da: 'Book en gratis demo, så viser vi, hvordan løsningen passer til din virksomhed.',
    answer_en: 'Book a free demo and we\'ll show you how the solution fits your business.',
    question_pt: 'Como começo a trabalhar convosco?',
    question_fr: 'Comment démarrer une collaboration avec vous ?',
    answer_pt: 'Marque uma demonstração gratuita e mostramos-lhe como a solução se adapta à sua empresa.',
    answer_fr: 'Réservez une démo gratuite et nous vous montrerons comment la solution s\'adapte à votre entreprise.',
  },
];
